### ISSUE TITLE
Cannot stop video (Mi Box)

### ISSUE THREAD

**Issue by johnodon** [kiall/android-tvheadend#115] opened 2017-01-18 19:11 UTC
I just found the TVH client for Live Channels (AWESOME!).  However, is there a proper way to stop playback?  I tried the Home button (the video continues to play in the background), the Back button (screen goes black for a second and playback continues)...pretty much everything...and can't find a way to stop the video.  Am I missing something or is this a bug?

Is there any other info I can provide?

John

**Comment by kiall** [comment] 2017-01-18 19:22
It's not a bug - all the user interactions are left up to Android TV, and one of decisions they made is to have Live Channels act like a TV would, always on until you turn the TV (or Android TV box) off or you change to an app that's not TV.. I'm not 100% certain I agree with the decision, but that's the way they went!

Opening any other app shold stop the video from playing in the background..

**Comment by kiall** [comment] 2017-01-18 19:26
Also, the back button causing the screen to go black for a few seconds sounds like a bug, either something in this app or in the Mi Box Android TV implementation.. nothing should interrupt the TV playback other than changing apps/channels/etc... It's likely Mi Box specific though, as it's not happening on the Shield/Nexus Player, so it'll be difficult to trace without the hardware :(

**Comment by stquinn** [comment] 2017-01-18 19:50
When on Android TV home screen, with live TV  playing in background...Press pause. TV will stop. 

On shield remote, double tap volume slider which Nvidia recently enabled as a pause function.

**Comment by johnodon** [comment] 2017-01-18 19:54
Understood and thank you for the feedback.  Unfortunately, the Mi Box has a simple remote that does not have a Play/Pause button.

John

**Comment by kiall** [comment] 2017-01-18 20:01
@stquinn - will have to try that! This isn't the first time I've heard people wondering about stopping playback, maybe if a few of TV box vendors add it, Google will add it as a standard feature for all...

**Comment by kiall** [comment] 2017-01-18 20:02
Anyway, as it's not an app bug (or feature were wanting to implement, as stock Android TV UI is a primary goal of the project) I'm going to close this out.

**Closed by kiall** 2017-01-18 20:02 UTC

**Comment by stquinn** [comment] 2017-01-18 20:33
@kiall Sorry I know this is closed... But just to add it is standard Android TV functionality. If you're remote doesn't have pause button nothing you can do but if you happen to use hdmi-cec most tv remotes have a play/pause button and that will stop playback as well. Works on Nexus player and Nvidia shield.

**Comment by johnodon** [comment] 2017-01-18 22:17
The double-tapping VOL works beautifully on the Shield TV.  Thank you stquinn.

**Comment by kiall** [comment] 2017-01-19 22:30
I also have a feeling this was the cause of my phantom pausing while using any app that supports pause and moving the remote..

**Comment by tunip** [comment] 2017-01-20 09:52
With the newest version of Live Channels, I only need to press the "back" button on the shield tv remote to stop the playback.

**Comment by seapoint** [comment] 2017-01-20 10:01
@tunip If I press "back" with the Shield(2015) Nougat Preview, playback continues in the background.

**Comment by tunip** [comment] 2017-01-20 11:27
@seapoint thats wired, I have also two Shields (2015) one with 3.3 and othe other one with 5.0 (Preview). On both if I press the back button the playback is stopping. This new behaviour was coming with Live Channels from 12th Jan 2017.

**Comment by seapoint** [comment] 2017-01-20 11:31
@tunip Live Channels updated - now I'm getting the playback stopped with back press. 
It's getting more WAF approval as we progress!  Off topic - the only MAJOR drawback I find with the Shield remote is the lack of a 'mute' button or function. The volume slider takes a +lot+ of getting used to but the lack of a mute is annoying.
