### ISSUE TITLE
Crashing with Sony Android 6 

### ISSUE THREAD

**Issue by aesthetiker** [kiall/android-tvheadend#84] opened 2016-11-03 19:29 UTC
Tried to run the app on Android 6 sony zd9 the program guide is crashing instantly when the app configures everything. As well on every app start in a loop. 
This is the TVH version running on my synology NAS HTS Tvheadend 4.1.2247. Tell me please how to provide logs from AndroidTV.

**Comment by stevellion** [comment] 2016-11-06 15:58
Seems exactly like my Sony Batavia TV.

**Comment by aesthetiker** [comment] 2016-11-07 12:35
Logfiles from the ZD9:
https://www.dropbox.com/s/elkkwsxkotxfik2/Androidtvh.txt?dl=0

**Comment by xi784** [comment] 2016-11-07 12:48
AndroidRuntime: Process: **com.sony.dtv.tvx**

**Comment by kiall** [comment] 2016-12-25 13:50
This appears to be a Sony bug, the crash is buried somewhere inside Sonty's replacement for the stock android Live Channels app, without getting my hands on one of these to test, it's really unlikely I'll find the underlying issue :(

Hopefully Sony releases a 6.0 build for my 2015 model!

**Comment by dkonerma** [comment] 2016-12-27 16:52
Exaclty what I see on my Sony running 6.0.1.

11-07 12:03:21.785  3757  3964 E AndroidRuntime: FATAL EXCEPTION: AsyncDbTask-0
11-07 12:03:21.785  3757  3964 E AndroidRuntime: Process: com.sony.dtv.tvx, PID: 3757
11-07 12:03:21.785  3757  3964 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
11-07 12:03:21.785  3757  3964 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: unknown error (code 0): INTEGER data in nativeGetBlob 

Apparently caused by fetching an integer as Blob... maybe something has been passed wrongly to the guide db (just guessing). Poor error handling then causes the crash of com.sony.dtv.tvx?

**Comment by dkonerma** [comment] 2016-12-27 17:32
To be sure, I just performed a factory reset, re-installed the app and re-configured all from scratch. Crash happens reproducibly during initial sync with TVH. So, indeed the app is currenty unusable on Sony Android 6.0.1 sets. Sad. :(

**Comment by UnsignedLong** [comment] 2017-01-01 14:46
Same thing is happening to me on my Sony XD75. HTTP Streaming was running fine, but since HTSP is implemented program guide crashes instantly.

**Comment by stevellion** [comment] 2017-01-01 15:22
I've now built an old 0.1.40 version (can download from below if you like) that seems to run very well on my Sony Bravia (XD75).  I'm not sure the big code difference in the EPG between 1.40 and the 0.2.x release, but for sure on Sony Android TV, 6.0.1, it just crashes when trying to load the EPG data.
https://dl.dropboxusercontent.com/u/49011675/tvheadend-live-1-40.apk

**Comment by kiall** [comment] 2017-01-01 15:26
@dkonerma Yea, the problem is - that's the Sony code fetching something, I've not been able to find out what it's fetching, or reproduce it on a 5.1.1 Sony, or 6.0 / 6.1 Nexus player or nVidia Shield..

**Comment by stevellion** [comment] 2017-01-01 15:27
Anything I can do remotely? - Presuming you don't live very near Milton Keynes... and can try on my TV :-)

**Comment by kiall** [comment] 2017-01-01 15:41
Can you give this some test builds a go to help narrow things down?

https://dl.dropboxusercontent.com/u/1400487/TVHeadend/ie.macinnes.tvheadend_v0.2.61-22-g2806828-release-unsigned-sony-test-1.apk - This doesn't process any program info, only channels..

**Comment by kiall** [comment] 2017-01-01 15:44
This second one doesn't process channel logos: https://dl.dropboxusercontent.com/u/1400487/TVHeadend/ie.macinnes.tvheadend_v0.2.61-23-g9940064-release-unsigned-sony-test-2.apk

(Also - It would be best to uninstall the app before each test build, to ensure a clean slate - e.g. installing the first one won't delete the existing program info right away, so would still crash until that data is removed - assuming that data is the issue)

**Comment by stevellion** [comment] 2017-01-01 21:32
Unfortunately, both are giving an error when trying to install..
It reports "Installing", then X App not installed.  I hope the log below covers it.

01-01 21:23:58.559  1694  2950 I ActivityManager: START u0 {dat=file:///storage/emulated/0/Download/ie.macinnes.tvheadend_v0.2.61-23-g9940064-release-unsigned-sony-test-2.apk cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress (has extras)} from uid 10020 on display 0^M
01-01 21:23:58.562  1694  2950 D PowerManagerNotifier: onWakeLockAcquired: flags=1, tag="*launch*", packageName=android, ownerUid=1000, ownerPid=1694, workSource=WorkSource{10020}^M
01-01 21:23:58.755  3215  5465 I RunningActivityManager: onTopActivityChanged^M
01-01 21:23:58.760  1705  1705 W Binder_2: type=1400 audit(0.0:1837): avc: denied { ioctl } for path="socket:[617914]" dev="sockfs" ino=617914 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0^M
01-01 21:23:58.760  1705  1705 W Binder_2: type=1400 audit(0.0:1838): avc: denied { ioctl } for path="socket:[617914]" dev="sockfs" ino=617914 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0^M
01-01 21:23:58.813  6508  6522 D mali_winsys: new_window_surface returns 0x3000^M
01-01 21:23:58.859  1694  3055 D PowerManagerNotifier: onWakeLockAcquired: flags=1, tag="AudioMix", packageName=media, ownerUid=1013, ownerPid=0, workSource=null^M
01-01 21:23:58.862  1694  1703 I art     : Background partial concurrent mark sweep GC freed 35017(3MB) AllocSpace objects, 82(1640KB) LOS objects, 33% free, 19MB/28MB, paused 2.802ms total 256.481ms^M
01-01 21:23:58.868  5598  5598 I Finsky  : [1] com.google.android.vending.verifier.PackageVerificationReceiver.onReceive(41): Verification requested, id = 3^M
01-01 21:23:58.880  1704  1704 W Binder_1: type=1400 audit(0.0:1839): avc: denied { ioctl } for path="socket:[617596]" dev="sockfs" ino=617596 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0^M
01-01 21:23:58.880  1704  1704 W Binder_1: type=1400 audit(0.0:1840): avc: denied { ioctl } for path="socket:[617596]" dev="sockfs" ino=617596 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0^M
01-01 21:23:58.883  1694  1714 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress: +308ms^M
01-01 21:23:58.935  6508  6522 D OpenGLRenderer: endAllStagingAnimators on 0xb8985d50 (RippleDrawable) with handle 0xb88fbd20^M
01-01 21:23:58.989  5598  5688 W Finsky  : [1494] com.google.android.vending.verifier.ak.b(461): Exception reading file:///storage/emulated/0/Download/ie.macinnes.tvheadend_v0.2.61-23-g9940064-release-unsigned-sony-test-2.apk in request id=3 java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference^M
01-01 21:23:58.993  5598  5598 I Finsky  : [1] com.google.android.vending.verifier.ak.c(194): Verification complete: id=3, package_name=ie.macinnes.tvheadend^M
01-01 21:23:58.995  5598  5598 I Finsky  : [1] com.google.android.vending.verifier.ak.g(17998): Verifying id=3, result=1^M
01-01 21:23:59.005  7038  7053 D DefContainer: Copying /storage/emulated/0/Download/ie.macinnes.tvheadend_v0.2.61-23-g9940064-release-unsigned-sony-test-2.apk to base.apk^M
01-01 21:23:59.088  1201  1201 W SurfaceFlinger: couldn't log to binary event log: overflow.^M
01-01 21:24:00.000  1694  2402 D PowerManagerNotifier: onWakeLockAcquired: flags=1073741825, tag="*alarm*", packageName=android, ownerUid=1000, ownerPid=1694, workSource=WorkSource{1000}^M
01-01 21:24:02.754  1694  1740 W PackageManager: Failed collect during installPackageLI^M
01-01 21:24:02.754  1694  1740 W PackageManager: android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl60366629.tmp/base.apk has no certificates at entry AndroidManifest.xml^M
01-01 21:24:02.754  1694  1740 W PackageManager:        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1105)^M

**Comment by vrouleau** [comment] 2017-01-02 14:10
Me also. sony test-2 fails to install on my x800d

**Comment by kiall** [comment] 2017-01-02 14:17
Humm, it's most likely that the 2 builds are unsigned. I'll sign and re-upload in the next few minutes.

**Comment by kiall** [comment] 2017-01-02 14:30
@stevellion @vrouleau first one to test: https://dl.dropboxusercontent.com/u/1400487/TVHeadend/ie.macinnes.tvheadend_v0.2.61-22-g2806828-release-sony-test-1.apk

second one still uploading

**Comment by kiall** [comment] 2017-01-02 14:32
And.. The second one: https://dl.dropboxusercontent.com/u/1400487/TVHeadend/ie.macinnes.tvheadend_v0.2.61-23-g9940064-release-sony-test-2.apk

Let me know if one or both or neither of these don't crash, which will let me narrow down what area if the code is causing an issue @stevellion @vrouleau

Also, please uninstall the app before install one of these, and uninstall again before installing the second! Any leftover data would invalidate the test!

**Comment by vrouleau** [comment] 2017-01-02 15:00
ok. test-1 started works. i was getting live tvs with channel logos using vlc. but then, after changing channels video stop. and it started charshing

**Comment by kiall** [comment] 2017-01-02 15:11
@vrouleau so, test-1 installed, setup, played video for a while, and is now crashing? If you reboot the TV, does it start working again? Can you gather some logs for the crash? Chances are, it's a second bug.

In the meantime, that's narrowed down the area where the (first) bug is :+1: Likely to less than 20 lines of code, so I'll triple check that area.

**Comment by kiall** [comment] 2017-01-02 15:21
@vrouleau I've made what could be a fix for the first crash? Can you give it a go and gather any logs? 

https://dl.dropboxusercontent.com/u/1400487/TVHeadend/ie.macinnes.tvheadend_v0.2.61-23-g3730f8b-release-sony-test-3.apk

**Comment by vrouleau** [comment] 2017-01-02 15:42
guide works . great!. i ve changed channels a few times at video keeps on working. i ll continue testing and report back

**Comment by kiall** [comment] 2017-01-02 15:59
Excellent! Let me know!

**Comment by stevellion** [comment] 2017-01-02 21:07
Yes, seems to run without initial crash.
2 observations though, that differs from 1.40:  a) it seemed to take a lot longer to do the initial channel scan/processing.  b) the channel numbers are not listed numerically anymore
it's also crashed a bit when using exoplayer, but vlc seems more stable after a reinstall.
[logcat.txt](https://github.com/kiall/android-tvheadend/files/681381/logcat.txt)

**Comment by kiall** [comment] 2017-01-02 22:13
re taking longer, we went from doing 1hr of data during that sync to 24 hours, I've been meaning to add a "quick sync" mode for that first sync, but it's been low on the list.

re out of order, damn, I was *really* hoping this issue would disappear come Sony's 6.0 builds :( TVHeadend sends us the channels in a random order over HTSP, and Sony for some reason isn't sorting them by channel number in the guide. Up/Down channel work as expected, but the guide shows out of order. It's been bugging on on my Sony 5.x TV, and should be fixed real soon now :)

**Comment by stevellion** [comment] 2017-01-02 22:55
some more crashes now, after I tried changing channels some more. Logcat attached.
I need to clear the data in the app and restart now as I can't get into any channel at the moment - either from the discover button, or the guide.
[logcat.txt](https://github.com/kiall/android-tvheadend/files/681463/logcat.txt)

**Comment by stevellion** [comment] 2017-01-03 09:00
Seems the problem is after using channel up/down.  Once I change channel it becomes unable to display picture (but getting sound), but constantly crashing.

**Comment by kiall** [comment] 2017-01-03 10:18
It looks like the same crash in the logcat, I wonder if you maybe have some old data from before the fix landed? Any attempt to read the broken data would likely cause it. Did you uninstall the app before installing a fixed version?

**Comment by kiall** [comment] 2017-01-03 10:28
Oh, and 0.1.66 includes the initial fix + has crash reporting enabled, which when it catches an issue (it doesn't if it's Sony's code exploding on our data), it gets more info for me! Prob best to ditch the test version and use that.

**Comment by stevellion** [comment] 2017-01-03 11:58
yes, I had to uninstall the app before it would run again - so hopefully 0.1.66 will show us.  Thanks for you time on this.

**Comment by stevellion** [comment] 2017-01-03 12:06
Just installing 0.2.66 now (previous typo's...) so may see crash reports.

**Comment by kiall** [comment] 2017-01-03 12:23
Nothing's come through, if any crashes have happened, it was likely in Sony's code. I'll take another look later and see if there are any other similar bugs somewhere...

**Comment by stevellion** [comment] 2017-01-03 12:31
Not crashing now :-)  Great.
Posting a logcat for another issue now.

**Comment by kiall** [comment] 2017-01-03 12:54
Okay, I'm going to go ahead and close this out. If the issue reappears, please reopen :)

**Closed by kiall** 2017-01-03 12:54 UTC
Labels: bug, device/Sony
